#!/usr/bin/env python
#
# file: agent_nextcloud_data
#
# created: 22/05/2022
#
# Author: Martin Hasin
# email: martin.hasin@gmail.com
#


def agent_nextcloud_data_arguments(params, hostname, ipaddress):
    args = ''

    args += " -u " + quote_shell_string(params["username"])
    args += " -p " + quote_shell_string(params["password"])
    args += " -t " + quote_shell_string(params["token"])
    if 'port' in params:
        args += " -P " + quote_shell_string(params["port"])
    else:
        args += " -P " + "443"


    if params.get("no_cert_check"):
        args += " --no-cert-check"
    if 'hostnamenextcloud' in params:
        args += " " + quote_shell_string(params["hostnamenextcloud"])
    else:
        args += " " + quote_shell_string(hostname)

    #args += " " + quote_shell_string(params["hostnamenextcloud"])
    #args += " " + quote_shell_string(hostname)
    #args += " " + quote_shell_string(ipaddress)
    return args


special_agent_info['nextcloud_data'] = agent_nextcloud_data_arguments



