#!/usr/bin/env python
#
# file: agent_nextcloud_data
#
# created: 22/05/2022
#
# Author: Martin Hasin
# email: martin.hasin@gmail.com
#


def agent_nextcloud_data_arguments(params, hostname, ipaddress):
    args = ''

    args += " -u " + quote_shell_string(params["username"])
    args += " -p " + quote_shell_string(params["password"])

    if params.get("no_cert_check"):
        args += " --no-cert-check"

    args += " " + quote_shell_string(hostname)
    #args += " " + quote_shell_string(ipaddress)
    return args


special_agent_info['nextcloud_data'] = agent_nextcloud_data_arguments



