#!/usr/bin/env python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
#
# file: nextcloud
#
# created: 22/05/2022
#
# Author: Martin Hasin
# email: martin.hasin@gmail.com
#


def inventory_nextcloud_data(info):
    for name, data in info:
        yield name, {}


def check_nextcloud_data(item, _no_params, info):
    for name, data in info:
        state = 0
        perfdata = []
        # No problem,
        # check output - status OK
        if name == item:
            if name == "Status":
                infotext = "Nextcloud status is: %s" % (
                    data)
                if data == "ok":
                    state = 0
                else:
                    state = 2
                yield state, infotext
        if name == item:
            if name == "debug":
                infotext = "Nextcloud debug is: %s" % (
                    data)
                if data == "no":
                    state = 0
                else:
                    state = 2
                yield state, infotext
        if name == item:
            if name == "apps_num_installed":
                infotext = "Nextcloud apps installed is: %s" % (
                    data)
                perfdata.append( (name, int(data)) )
                yield state, infotext, perfdata

        if name == item:
            if name == "num_updates_available":
                infotext = "Nextcloud updates available is: %s" % (
                    data)
                if data == "0":
                    state = 0
                else:
                    state = 2

                perfdata.append( (name, int(data)) )
                yield state, infotext, perfdata

        if name == item:
            if name == "storage_num_users":
                infotext = "Nextcloud number users is: %s" % (
                    data)
                perfdata.append( (name, int(data)) )
                yield state, infotext, perfdata

        if name == item:
            if name == "storage_num_files":
                infotext = "Nextcloud number files is: %s" % (
                    data)
                perfdata.append( (name, int(data)) )
                yield state, infotext, perfdata

        if name == item:
            if name == "storage_num_storages":
                infotext = "Nextcloud number storages is: %s" % (
                    data)
                perfdata.append( (name, int(data)) )
                yield state, infotext, perfdata

        if name == item:
            if name == "storage_num_storages_local":
                infotext = "Nextcloud number storages local is: %s" % (
                    data)
                perfdata.append( (name, int(data)) )
                yield state, infotext, perfdata

        if name == item:
            if name == "storage_num_storages_home":
                infotext = "Nextcloud number storages home is: %s" % (
                    data)
                perfdata.append( (name, int(data)) )
                yield state, infotext, perfdata

        if name == item:
            if name == "storage_num_storages_other":
                infotext = "Nextcloud number storages other is: %s" % (
                    data)
                perfdata.append( (name, int(data)) )
                yield state, infotext, perfdata

        if name == item:
            if name == "num_shares":
                infotext = "Nextcloud number shares is: %s" % (
                    data)
                perfdata.append( (name, int(data)) )
                yield state, infotext, perfdata

        if name == item:
            if name == "num_shares_user":
                infotext = "Nextcloud number shares user is: %s" % (
                    data)
                perfdata.append( (name, int(data)) )
                yield state, infotext, perfdata

        if name == item:
            if name == "num_shares_groups":
                infotext = "Nextcloud number shares groups is: %s" % (
                    data)
                perfdata.append( (name, int(data)) )
                yield state, infotext, perfdata

        if name == item:
            if name == "num_shares_link":
                infotext = "Nextcloud number shares link is: %s" % (
                    data)
                perfdata.append( (name, int(data)) )
                yield state, infotext, perfdata

        if name == item:
            if name == "num_shares_mail":
                infotext = "Nextcloud number shares mail is: %s" % (
                    data)
                perfdata.append( (name, int(data)) )
                yield state, infotext, perfdata

        if name == item:
            if name == "num_shares_room":
                infotext = "Nextcloud number shares room is: %s" % (
                    data)
                perfdata.append( (name, int(data)) )
                yield state, infotext, perfdata

        if name == item:
            if name == "num_shares_link_no_password":
                infotext = "Nextcloud number shares link no password is: %s" % (
                    data)
                perfdata.append( (name, int(data)) )
                yield state, infotext, perfdata

        if name == item:
            if name == "num_fed_shares_sent":
                infotext = "Nextcloud number fed shares sent is: %s" % (
                    data)
                perfdata.append( (name, int(data)) )
                yield state, infotext, perfdata

        if name == item:
            if name == "num_fed_shares_received":
                infotext = "Nextcloud number fed shares received is: %s" % (
                    data)
                perfdata.append( (name, int(data)) )
                yield state, infotext, perfdata

        if name == item:
            if name == "permissions_3_17":
                infotext = "Nextcloud permissions_3_17 is: %s" % (
                    data)
                perfdata.append( (name, int(data)) )
                yield state, infotext, perfdata

        if name == item:
            if name == "last5minutes":
                infotext = "Nextcloud last5minutes active user is: %s" % (
                    data)
                perfdata.append( (name, int(data)) )
                yield state, infotext, perfdata

        if name == item:
            if name == "last1hour":
                infotext = "Nextcloud last1hour active user is: %s" % (
                    data)
                perfdata.append( (name, int(data)) )
                yield state, infotext, perfdata

        if name == item:
            if name == "last24hours":
                infotext = "Nextcloud last24hours active user is: %s" % (
                    data)
                perfdata.append( (name, int(data)) )
                yield state, infotext, perfdata



            
 #       yield state, infotext


check_info["nextcloud_data"] = {
    'check_function': check_nextcloud_data,
    'inventory_function': inventory_nextcloud_data,
    'service_description': 'Nextcloud %s',
    'has_perfdata' :        True,
    'group': 'nextcloud_data'
    }
